config/routes.rb
RailsSaas::Application.routes.draw do
  use_doorkeeper

  devise_for :users, :controllers => { :invitations => 'users/invitations', :registrations => 'registrations' }

  namespace :api do
    api :version => 1 do
      resources :products
      resources :sync, :only => [:index]
    end
  end

  root :to => 'home#index'
  get 'tour' => 'home#tour'
  get 'pricing' => 'home#pricing'
  get 'why' => 'home#why'
  get 'testimonials' => 'home#testimonials'
  get 'about' => 'home#about'

  get 'content/silver'
  get 'content/gold'
  get 'content/platinum'

  resources :products
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :tenant_id
  #has_secure_password
  validates_uniqueness_of :email, scope: :tenant_id

  default_scope { where(tenant_id: Tenant.current_id) if Tenant.current_id }

  def self.authenticate!(username, password)
    return nil if username.blank? || password.blank?

    if (user = User.find_by_email(username))
      return user if user.valid_password?(password)
    end

    nil
  end

  def invite!(invited_by = nil)
    logger.info "User invite: " + Tenant.current_id.to_s
    self.tenant_id = Tenant.current_id
    super invited_by
  end

  def self.blacklist_keys
    @blacklist_keys ||= super - ["id"]
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  around_filter :scope_current_tenant

  private

  def current_tenant
    Tenant.find_by_subdomain! request.subdomain
  end

  def scope_current_tenant
    Tenant.current_id = current_tenant.id
    yield
  ensure
    Tenant.current_id = nil
  end
end

app/controllers/users_controller.rb
class UsersController < TenantApplicationController

  def index
    @users = User.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
end

app/helpers/users/invitations_helper.rb
module Users::InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h3>Listing users for <%= current_tenant.name %></h3>

<table class="table table-condensed table-striped">
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Invite User', new_user_invitation_path, :class => 'btn' %>

app/views/users/invite.html.erb
<h1>Invite user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', users_path %>