config/routes.rb
RailsSaas::Application.routes.draw do
  use_doorkeeper

  devise_for :users, :controllers => { :invitations => 'users/invitations', :registrations => 'registrations' }

  namespace :api do
    api :version => 1 do
      resources :products
      resources :sync, :only => [:index]
    end
  end

  root :to => 'home#index'
  get 'tour' => 'home#tour'
  get 'pricing' => 'home#pricing'
  get 'why' => 'home#why'
  get 'testimonials' => 'home#testimonials'
  get 'about' => 'home#about'

  get 'content/silver'
  get 'content/gold'
  get 'content/platinum'

  resources :products
  resources :users

end

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-message <%= alert_css_class(type) %>" data-alert="alert">
    <a class="close" data-dismiss="alert" href="#">&times;</a>
    <p><%= message %></p>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "rails-saas", root_path, :class => 'brand' %>
      <% if user_signed_in? %>
        <ul class="nav">
          <li><%= link_to('Products', products_path) %></li>
          <% if current_user.has_role? :admin %>
            <li><%= link_to('Users', users_path) %></li>
          <% end %>
        </ul>
      <% else %>
        <ul class="nav">
          <li><%= link_to('Tour', tour_path) %></li>
          <li><%= link_to('Pricing', pricing_path) %></li>
          <li><%= link_to('Why?', why_path) %></li>
          <li><%= link_to('Testimonials', testimonials_path) %></li>
          <li><%= link_to('About', about_path) %></li>
        </ul>
      <% end %>
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to('Edit account', edit_user_registration_path) %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
        <% else %>
          <li><%= link_to('Login', new_user_session_path) %></li>
          <li><%= link_to('Sign up', new_user_registration_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Saas</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="home">
  <%= render 'layouts/navigation' %>
  <article class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </article>
</body>
</html>